export const ACTION_REACTION_FETCHED = 'ACTION_REACTION_FETCHED';

export const ACTION_CHANGE_QUERY = 'ACTION_CHANGE_QUERY';

export const ACTION_CHANGE_STATE = 'ACTION_CHANGE_STATE';

export const ACTION_START_SHARING_REACTION = 'ACTION_START_SHARING_REACTION';

export const ACTION_REACTION_SHARED = 'ACTION_REACTION_SHARED';

export const API_REACTION_ENDPOINT = '/api/v1/search/';

export const ROUTE_FIND_REACTION = 'ROUTE_FIND_REACTION';

export const ROUTE_ABOUT = 'ROUTE_ABOUT';

export const STATE_EMPTY_QUERY = 'STATE_EMPTY_QUERY';

export const STATE_SEARCHING = 'STATE_SEARCHING';

export const STATE_NOT_FOUND = 'STATE_NOT_FOUND';

export const STATE_FOUND = 'STATE_FOUND';

export const HEADER_COLOR = '#4078c0';

export const SHARING_NOT_AVAILABLE = 'SHARING_NOT_AVAILABLE';

export const SHARING_AVAILABLE = 'SHARING_AVAILABLE';
