export const ACTION_REACTION_FETCHED = 'ACTION_REACTION_FETCHED';

export const ACTION_CHANGE_QUERY = 'ACTION_CHANGE_QUERY';

export const ACTION_START_SHARING_REACTION = 'ACTION_START_SHARING_REACTION';

export const ACTION_REACTION_SHARED = 'ACTION_REACTION_SHARED';

export const API_REACTION_ENDPOINT = '/api/v1/search/';

export const ROUTE_FIND_REACTION = 'ROUTE_FIND_REACTION';

export const ROUTE_ABOUT = 'ROUTE_ABOUT';

export const UNDERLAY_COLOR = '#00ACC1';
